apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: deny-all-traffic
  namespace: fridge-api
spec:
  endpointSelector: {}
  ingress:
    - {}
  egress:
    - {}
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-server-traffic
  namespace: fridge-api
spec:
  endpointSelector:
    matchLabels:
      app: fridge-api-server
  ingress:
    - fromEndpoints:
      - matchLabels:
          app: server
          k8s:io.kubernetes.pod.namespace: argo-server
      toPorts:
        - ports:
          - port: "2746"
            protocol: TCP
    - fromEndpoints:
      - matchLabels:
          v1.min.io/tenant: argo-artifacts
          k8s:io.kubernetes.pod.namespace: argo-artifacts
      toPorts:
        - ports:
          - port: "9000"
            protocol: TCP
    - fromEntities:
      - remote-node
      toPorts:
        - ports:
          - port: "8000"
            protocol: TCP
  egress:
    - toEndpoints:
      - matchLabels:
          app: server
          k8s:io.kubernetes.pod.namespace: argo-server
      toPorts:
        - ports:
          - port: "2746"
            protocol: TCP
    - toEndpoints:
      - matchLabels:
          v1.min.io/tenant: argo-artifacts
          k8s:io.kubernetes.pod.namespace: argo-artifacts
      toPorts:
        - ports:
          - port: "9000"
            protocol: TCP
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: minio-operator
      toPorts:
        - ports:
          - port: "4223"
            protocol: TCP
    - toEndpoints:
      - matchLabels:
          k8s-app: kube-dns
          k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
          - port: "53"
            protocol: ANY
          rules:
            dns:
              - matchPattern: "argo-workflows-server.argo-server.svc.cluster.local"
              - matchPattern: "minio.argo-artifacts.svc.cluster.local"
              - matchPattern: "sts.minio-operator.svc.cluster.local"
    - toFQDNs:
      - matchPattern: "argo-workflows-server.argo-server.svc.cluster.local"
      - matchPattern: "minio.argo-artifacts.svc.cluster.local"
      - matchPattern: "sts.minio-operator.svc.cluster.local"
